name: hrms_flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.18.1
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  open_file: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/maleavatar.jpg
